server:
 port: 8072

# Spring Boot Actuator Settings
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoints.enabled-by-default: true

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

# spring:
#   cloud:
#     gateway:
#       discovery.locator:
#         enabled: true
#         lowerCaseServiceId: true

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
