message: "I AM THE DEFAULT"


# Spring Data JPA and Hibernate Settings
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: none
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  database:
    driverClassName: com.mysql.cj.jdbc.Driver

# Spring Boot Actuator Settings
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoints.enabled-by-default: true
