message: "I AM DEV"

# DataSource settings: set here your own configurations for the database 
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data?sslmode=disable
    username: postgres
    password: {cipher}a38fe720f7d1ce5bd06ea8b081139ea1a9db3617bec84aa25772ff1a124d8fb7
