# Spring database settiing (I'll update later)
spring:
  database:
    driverClassName: org.postgresql.Driver


# Spring Boot Actuator Settings
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoints.enabled-by-default: true

server:
  port: 8081

server:
  port: 8070
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka/"
  server:
    waitTimeInMsWhenSyncEmpty: 5
